-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgsQgtXIZadsFpJogU
OyHTKhlor4SPSmj/nmMbYVHq7oKgCgYIKoZIzj0DAQehRANCAASqisAeoaV6fUs1
hrd2MZx4AhJHG0viUq4aKpHqq7vzX+tjHhPefESIimLCxQP3M3RO04QreOms53lN
CAZzArkF
-----END PRIVATE KEY-----